
name: Test Commit

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: preview-pages-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    name: Run

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run something
        run: "touch index.md && echo 'test2' >> index.md"

      - name: Generate token
        id: generate-token
        uses: tibdex/github-app-token@v1.8.0
        with:
          app_id: ${{ secrets.RAJYAN_BOT_APP_ID }}
          private_key: ${{ secrets.RAJYAN_BOT_PRIVATE_KEY }}

      - name: Preview Pages
        uses: rajyan/preview-pages@v0.1.6
        with:
          github-token: ${{ steps.generate-token.outputs.token }}
          pages-organization: rajyan
          pages-repository: coverage-report
          path: index.md
